sudo: required
services:
  - docker

before_install:
 - docker build -f Dockerfile.dev -t blodemaster/docker-learning .


script:
 - docker run blodemaster/docker-learning npm run test -- --coverage


deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-learning"
  env: "DockerLearning-env"
  bucket_name: "elasticbeanstalk-us-west-2-349616744509"
  bucket_path: "docker-learning"
  on:
    branch: master
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"